import type { Metadata } from 'next';
import { Sora } from 'next/font/google';
import './globals.css';
import {
  NextInterfaceProvider,
  ReactQueryProvider,
  ThemeProvider,
} from '@/components/providers';
import { Header } from '@/components/header';

const sora = Sora({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactQueryProvider>
      <html lang="en">
        <body className={sora.className}>
          <ThemeProvider>
            <NextInterfaceProvider>
              <Header />
              <main className="container mx-auto">{children}</main>
            </NextInterfaceProvider>
          </ThemeProvider>
        </body>
      </html>
    </ReactQueryProvider>
  );
}
